name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  claude:
    # Only run if @claude is mentioned or on PR open/sync
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'pull_request' && github.event.action == 'opened')
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better context
      
      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          # API Authentication
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Model Configuration
          claude_args: |
            --max-turns 15
            --model claude-sonnet-4-5-20250929
          
          # Optional: Custom prompt for PR reviews
          # If not provided, Claude will respond to the @claude mention
          # Uncomment and customize for automatic PR reviews:
          # prompt: |
          #   Review this pull request for:
          #   1. Security vulnerabilities (P0 priority)
          #   2. Compliance with HERMES coding standards (CLAUDE.md)
          #   3. Attorney-client privilege data handling
          #   4. Performance issues in voice pipeline
          #   5. Missing tests or documentation
          #   
          #   Focus on identifying P0 and P1 issues. For P2/P3 issues,
          #   provide brief suggestions but don't block the PR.
          #   
          #   For any security concerns, mark them clearly as [P0 BLOCKER].

      - name: Comment on rate limit
        if: failure() && contains(github.event.comment.body, '@claude')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Claude Code hit a rate limit or encountered an error. Please try again in a few minutes, or check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            })